2023-12-23 05:44:36,701 ERROR: Exception on /auth/logout [GET] [in /home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py : 825]
Traceback (most recent call last):
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/auth/routes.py", line 49, in logout
    return redirect(url_for('main.index'))
                    ^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/helpers.py", line 222, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py", line 1071, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/flask/app.py", line 1060, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/flask_environment/lib/python3.11/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-12-23 05:44:46,012 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 53]
2023-12-27 06:42:54,596 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 55]
