2024-01-04 16:20:50,459 ERROR: Exception on /api/users/3/chats/6 [PUT] [in /home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py : 825]
Traceback (most recent call last):
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/api/users.py", line 32, in update_chat
    conversation.from_dict(id,data=data)
  File "/home/py_sama/rapid_care/app/models.py", line 188, in from_dict
    returned_link = [return_link(keyword) for keyword in search_keywords]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/models.py", line 188, in <listcomp>
    returned_link = [return_link(keyword) for keyword in search_keywords]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/videos/videos_functions.py", line 51, in return_link
    return {search_result[0].all()[0].name : search_result[0].all()[0].url}
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-01-04 16:21:52,810 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 80]
2024-01-04 16:24:07,264 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 80]
2024-01-04 16:25:20,173 ERROR: Exception on /api/users/3/chats/5 [PUT] [in /home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py : 825]
Traceback (most recent call last):
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/api/users.py", line 32, in update_chat
    conversation.from_dict(id,data=data)
  File "/home/py_sama/rapid_care/app/models.py", line 188, in from_dict
    returned_link = [return_link(keyword) for keyword in search_keywords]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/models.py", line 188, in <listcomp>
    returned_link = [return_link(keyword) for keyword in search_keywords]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/videos/videos_functions.py", line 50, in return_link
    return {search_result[0].all()[0].name : search_result[0].all()[0].url}
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-01-04 16:26:53,287 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 80]
2024-01-04 16:27:22,695 ERROR: Exception on /api/users/3/chats/5 [PUT] [in /home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py : 825]
Traceback (most recent call last):
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/api/users.py", line 32, in update_chat
    conversation.from_dict(id,data=data)
  File "/home/py_sama/rapid_care/app/models.py", line 188, in from_dict
    returned_link = [return_link(keyword) for keyword in search_keywords]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/models.py", line 188, in <listcomp>
    returned_link = [return_link(keyword) for keyword in search_keywords]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/videos/videos_functions.py", line 50, in return_link
    return {search_result[0].all()[0].name : search_result[0].all()[0].url}
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-01-04 16:28:47,304 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 80]
2024-01-04 16:29:07,935 ERROR: Exception on /api/users/3/chats/5 [PUT] [in /home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py : 825]
Traceback (most recent call last):
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/api/users.py", line 32, in update_chat
    conversation.from_dict(id,data=data)
  File "/home/py_sama/rapid_care/app/models.py", line 188, in from_dict
    returned_link = [return_link(keyword) for keyword in search_keywords]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/models.py", line 188, in <listcomp>
    returned_link = [return_link(keyword) for keyword in search_keywords]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/videos/videos_functions.py", line 51, in return_link
    return {search_result[0].all()[0].name : search_result[0].all()[0].url}
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-01-04 16:31:51,827 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 80]
2024-01-04 16:39:37,839 ERROR: Exception on /api/users/3/chats/5 [PUT] [in /home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py : 825]
Traceback (most recent call last):
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/rapid_care_environment/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/api/users.py", line 32, in update_chat
    conversation.from_dict(id,data=data)
  File "/home/py_sama/rapid_care/app/models.py", line 188, in from_dict
    returned_link = [return_link(keyword) for keyword in search_keywords]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/models.py", line 188, in <listcomp>
    returned_link = [return_link(keyword) for keyword in search_keywords]
                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/py_sama/rapid_care/app/videos/videos_functions.py", line 51, in return_link
    return {search_result[0].all()[0].name : search_result[0].all()[0].url}
            ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-01-04 16:49:57,078 INFO: hub_startup [in /home/py_sama/rapid_care/app/__init__.py : 80]
